name: Run Pytest

on:
  push:
    branches:
      - dev

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Setup Default Databricks CLI Profile
        run: |
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host = ${{ secrets.DATABRICKS_HOST }}" >> ~/.databrickscfg
          echo "token = ${{ secrets.DATABRICKS_TOKEN }}" >> ~/.databrickscfg
          echo "serverless_compute_id = auto" >> ~/.databrickscfg
      
      - name: Run Pytest
        run: python -m pytest . -v -p no:cacheprovider --disable-warnings --cov=src/ --cov-report=term-missing